### ISSUE TITLE
[Todo] Check support for Steam versions

### ISSUE THREAD

**Issue by dwatteau** [dwatteau/scummtr#53]
Steam sells some LucasArts titles, such as Indy3, Indy4, Loom, The Dig or Sam & Max. Some of them are a bit different from the original floppy/CD releases (which is what GOG mostly uses).

The ScummTR tools predate the Steam versions, which appear to embed the index files (000.LFL and so on) into the main executables.

(For example, for my Steam version of Loom, `000.LFL` is at offset 170464+8307 of the `Loom` macOS binary file.)

I don't think that the ScummTR tools should to find this content themselves, but we should at least document how to do this somewhere.

References:

https://github.com/symm/LAAExtract  
https://github.com/scummvm/scummvm/blob/master/engines/scumm/detection_steam.h

Games to be checked:

- [ ] Loom (Steam/Windows)
- [x] Loom (Steam/macOS)
- [ ] Indy3 (Steam/Windows)
- [ ] Indy3 (Steam/macOS)
- [ ] Indy4 (Steam/Windows)
- [ ] Indy4 (Steam/macOS)
- [ ] Sam & Max (Steam/Windows)
- [ ] Sam & Max (Steam/macOS)
- [ ] The Dig (Steam/Windows)
- [ ] The Dig (Steam/macOS)

**Comment by dwatteau** [comment]
See also:
https://forums.scummvm.org/viewtopic.php?t=16576

As for Sam & Max, it looks like Steam just uses ScummVM so the resource files are probably unmodified.
